interface HeadProps {
    pathname?: string;
    }

    export const Head = ({ pathname = '/' }: HeadProps) => {
      const siteUrl = 'https://www.114barwhiskeyrow.com/';
        const businessName = 'One Fourteen';
          const businessDescription = 'One Fourteen is a late night bar on Whiskey Row in downtown Louisville. Open Tue–Sun until 2am. Walk-ins only. DJs and game day sound on.';
            const phone = '+1-502-907-1400';

              const pageSEO: Record<string, { title: string; description: string; canonical: string }> = {
                  '/': {
                        title: 'One Fourteen | Late-Night Bar on Whiskey Row, Louisville KY',
                              description: 'Late-night bar on Whiskey Row, steps from the KFC Yum Center. Tue–Sun, 4pm–2am. Walk-ins only. 21+. DJs, game-day sound on, Sunday industry night.',
                                    canonical: 'https://www.114barwhiskeyrow.com/',
                                        },
                                            '/visit': {
                                                  title: 'Visit One Fourteen | Hours, Parking & Directions on Whiskey Row',
                                                        description: 'Find One Fourteen at 114 W Main St on Whiskey Row, across from the KFC Yum Center. Open Tue–Sun, 4pm–2am. Walk-ins only. Get directions, parking, what to expect.',
                                                              canonical: 'https://www.114barwhiskeyrow.com/visit',
                                                                  },
                                                                      '/events': {
                                                                            title: 'Events at One Fourteen | DJs, Industry Night & Game Days on Whiskey Row',
                                                                                  description: 'Weekly DJs, Sunday Industry Night, and game-day sound on at One Fourteen, a late-night bar on Whiskey Row in downtown Louisville. See what is on tonight.',
                                                                                        canonical: 'https://www.114barwhiskeyrow.com/events',
                                                                                            },
                                                                                                '/gallery': {
                                                                                                      title: 'Gallery | Inside One Fourteen Bar on Whiskey Row, Louisville',
                                                                                                            description: 'Photos from One Fourteen, the late-night room on Whiskey Row. Cocktails, the Yard, DJs, and downtown Louisville nightlife.',
                                                                                                                  canonical: 'https://www.114barwhiskeyrow.com/gallery',
                                                                                                                      },
                                                                                                                          '/contact': {
                                                                                                                                title: 'Contact One Fourteen | Whiskey Row Bar in Downtown Louisville',
                                                                                                                                      description: 'Contact One Fourteen on Whiskey Row in downtown Louisville. (502) 907-1400, info@114whiskeyrow.com, Tue–Sun, 4pm–2am. Walk-ins only. 21+.',
                                                                                                                                            canonical: 'https://www.114barwhiskeyrow.com/contact',
                                                                                                                                                },
                                                                                                                                                  };

                                                                                                                                                    const normalized = pathname && pathname !== '/' ? pathname.replace(/\/$/, '') : '/';
                                                                                                                                                      const seo = pageSEO[normalized] || pageSEO['/'];

                                                                                                                                                        const logoUrl = 'https://static.wixstatic.com/media/528274_112a88f0f95c4632b6449db5f7575a0b~mv2.png';

                                                                                                                                                          const localBusinessSchema = {
                                                                                                                                                              '@context': 'https://schema.org',
                                                                                                                                                                  '@type': 'BarOrPub',
                                                                                                                                                                      'name': businessName,
                                                                                                                                                                          'description': businessDescription,
                                                                                                                                                                              'url': seo.canonical,
                                                                                                                                                                                  'telephone': phone,
                                                                                                                                                                                      'servesCuisine': 'Bar',
                                                                                                                                                                                          'image': logoUrl,
                                                                                                                                                                                              'address': {
                                                                                                                                                                                                    '@type': 'PostalAddress',
                                                                                                                                                                                                          'streetAddress': '114 W Main St',
                                                                                                                                                                                                                'addressLocality': 'Louisville',
                                                                                                                                                                                                                      'addressRegion': 'KY',
                                                                                                                                                                                                                            'postalCode': '40202',
                                                                                                                                                                                                                                  'addressCountry': 'US'
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                          'geo': {
                                                                                                                                                                                                                                                '@type': 'GeoCoordinates',
                                                                                                                                                                                                                                                      'latitude': '38.2526',
                                                                                                                                                                                                                                                            'longitude': '-85.7585'
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                    'openingHoursSpecification': [
                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                  '@type': 'OpeningHoursSpecification',
                                                                                                                                                                                                                                                                                          'dayOfWeek': ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                                                                                                                                                                                                                                                                                                  'opens': '16:00',
                                                                                                                                                                                                                                                                                                          'closes': '02:00'
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                        'priceRange': '$$',
                                                                                                                                                                                                                                                                                                                            'sameAs': [
                                                                                                                                                                                                                                                                                                                                  'https://www.instagram.com/onefourteenwhiskeyrow/'
                                                                                                                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                          const organizationSchema = {
                                                                                                                                                                                                                                                                                                                                              '@context': 'https://schema.org',
                                                                                                                                                                                                                                                                                                                                                  '@type': 'Organization',
                                                                                                                                                                                                                                                                                                                                                      'name': businessName,
                                                                                                                                                                                                                                                                                                                                                          'url': siteUrl,
                                                                                                                                                                                                                                                                                                                                                              'logo': logoUrl,
                                                                                                                                                                                                                                                                                                                                                                  'sameAs': [
                                                                                                                                                                                                                                                                                                                                                                        'https://www.instagram.com/onefourteenwhiskeyrow/'
                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                'contactPoint': {
                                                                                                                                                                                                                                                                                                                                                                                      '@type': 'ContactPoint',
                                                                                                                                                                                                                                                                                                                                                                                            'contactType': 'Customer Service',
                                                                                                                                                                                                                                                                                                                                                                                                  'telephone': phone
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                                                                                                                                                                                                    <title>{seo.title}</title>
                                                                                                                                                                                                                                                                                                                                                                                                                          <meta name="description" content={seo.description} />
                                                                                                                                                                                                                                                                                                                                                                                                                                <link rel="canonical" href={seo.canonical} />

                                                                                                                                                                                                                                                                                                                                                                                                                                      <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                            <meta name="author" content={businessName} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <meta property="og:type" content="website" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <meta property="og:title" content={seo.title} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <meta property="og:description" content={seo.description} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <meta property="og:url" content={seo.canonical} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <meta property="og:site_name" content={businessName} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <meta property="og:image" content={logoUrl} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <meta property="og:image:width" content="1024" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <meta property="og:image:height" content="1024" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <meta property="og:locale" content="en_US" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <meta name="twitter:card" content="summary_large_image" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <meta name="twitter:title" content={seo.title} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <meta name="twitter:description" content={seo.description} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <meta name="twitter:image" content={logoUrl} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .skip-link { position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; overflow: hidden; z-index: 9999; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .skip-link:focus { position: fixed; left: 1rem; top: 1rem; width: auto; height: auto; padding: 0.75rem 1rem; background: #fff; color: #000; font-weight: 700; border: 2px solid #FF5722; text-decoration: none; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    *:focus-visible { outline: 3px solid #FF5722 !important; outline-offset: 2px !important; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
}
